using GhostSlacking.Core;

namespace GhostSlacking.App;

internal static class UiText
{
    public static bool IsChinese(UiLanguage language) => language == UiLanguage.Chinese;

    public static string LanguageName(UiLanguage language) => IsChinese(language) ? "中文" : "English";

    public static string State(UiLanguage language, GhostState state) => language switch
    {
        UiLanguage.Chinese => state switch
        {
            GhostState.Idle => "空闲",
            GhostState.Picking => "选择窗口",
            GhostState.Preparing => "准备中",
            GhostState.Ghost => "Ghost 隐藏",
            GhostState.Reveal => "Reveal 显示",
            GhostState.Visible => "窗口显示",
            GhostState.Restoring => "恢复中",
            GhostState.RecoveryError => "恢复错误",
            _ => state.ToString()
        },
        _ => state switch
        {
            GhostState.Idle => "Idle",
            GhostState.Picking => "Picking",
            GhostState.Preparing => "Preparing",
            GhostState.Ghost => "Ghost",
            GhostState.Reveal => "Reveal",
            GhostState.Visible => "Visible",
            GhostState.Restoring => "Restoring",
            GhostState.RecoveryError => "Recovery error",
            _ => state.ToString()
        }
    };

    public static string Text(UiLanguage language, string key) => language == UiLanguage.Chinese ? key switch
    {
        "status" => "状态：{0}（{1}）",
        "pick" => "选择窗口",
        "toggle" => "切换窗口显隐",
        "restore" => "恢复窗口",
        "restoreAll" => "恢复所有窗口",
        "settings" => "设置",
        "updateAvailableTray" => "发现新版本 {0}",
        "updateAvailableNotification" => "发现新版本 {0}，点击查看更新内容。",
        "exit" => "退出",
        "startupReady" => "GhostSlacking 已启动，正在系统托盘运行。",
        "clickToPick" => "窗口选择已开启。请单击目标窗口，或按 Esc 取消。",
        "pickCancelled" => "已取消选择窗口。",
        "noWindow" => "未能选择此窗口。请单击一个可见的应用窗口后重试。",
        "windowSelected" => "已隐藏 {0}。使用 {1} 可在光标附近查看。",
        "restoreSome" => "部分窗口未能恢复。请再次执行“恢复所有窗口”；若仍失败，请查看日志。",
        "pickFailed" => "无法开始选择窗口。请重试；若问题持续，请重启 GhostSlacking。",
        "selectionStateCaptureFailed" => "无法选择该窗口。未能安全保存窗口状态，未作任何更改。",
        "ghostActivationFailed" => "无法隐藏所选窗口。已尝试恢复原状态，请确认窗口显示正常。",
        "windowPlacementCorrectionFailed" => "无法保持窗口位置。正在恢复窗口，请确认其显示正常。",
        "hideWindowFailed" => "无法隐藏目标窗口。请执行“恢复窗口”退出隐藏模式。",
        "revealWindowFailed" => "无法更新局部显示。请重试，或执行“恢复窗口”。",
        "restoreFailed" => "未能完整恢复窗口。请再次执行“恢复所有窗口”，或查看日志。",
        "operationFailed" => "操作未能完成。请重试；若仍失败，请查看日志。",
        "settingsOpenFailed" => "无法打开设置。请重试；若仍失败，请查看日志。",
        "updateWindowOpenFailed" => "无法打开更新窗口。请重试；若仍失败，请查看日志。",
        "unexpected" => "应用遇到意外错误。请重试；若仍失败，请查看日志。",
        "title" => "GhostSlacking 设置",
        "settingsCaption" => "偏好设置",
        "settingsHint" => "更改将在保存后生效",
        "collapseSidebar" => "收起侧栏",
        "expandSidebar" => "展开侧栏",
        "revealSettings" => "显示与操作",
        "revealSettingsDescription" => "调整窗口的 Reveal 外观与 Peek 操作方式",
        "hotkeySettings" => "快捷键",
        "hotkeySettingsDescription" => "为常用操作设置全局组合键",
        "generalSettings" => "常规",
        "generalSettingsDescription" => "管理外观、启动、恢复、语言和诊断选项",
        "about" => "关于",
        "aboutDescription" => "查看版本、项目链接和软件更新",
        "aboutGhostSlacking" => "关于 GHOSTSLACKING",
        "aboutProductDescription" => "轻量级 Windows 窗口隐藏与局部查看工具",
        "sourceRepository" => "GitHub 项目",
        "releasePage" => "发布页",
        "softwareUpdate" => "软件更新",
        "updateChannel" => "更新通道",
        "updateChannelDescription" => "默认只接收稳定版；测试通道会包含 beta 和 RC 版本。",
        "updateChannelStable" => "稳定版",
        "updateChannelTest" => "测试版（包含预发布）",
        "currentVersion" => "当前版本：{0}",
        "latestVersion" => "最新版本：{0}",
        "lastSuccessfulUpdateCheck" => "上次成功检查：{0}",
        "noSuccessfulUpdateCheck" => "尚无成功检查记录",
        "checkUpdates" => "检查更新",
        "checkingUpdates" => "正在从 GitHub Releases 检查更新…",
        "upToDate" => "当前已是最新可用版本。",
        "updateNotChecked" => "尚未在本次运行中检查更新。",
        "updateAvailableDescription" => "版本 {0} 已发布，可下载并安装。",
        "updateSkippedDescription" => "已跳过版本 {0}；仍可立即安装或恢复提醒。",
        "downloadingUpdate" => "正在下载更新… {0}%",
        "verifyingUpdate" => "正在校验安装包完整性…",
        "startingInstaller" => "安装包已校验，正在准备自动升级…",
        "updateFailed" => "无法检查、下载或启动更新。请检查网络后重试，或查看发布页面。",
        "updateCompleted" => "GhostSlacking 已成功升级到版本 {0}。",
        "updateCancelled" => "已取消软件更新，GhostSlacking 已恢复运行。",
        "automaticUpdateFailed" => "版本 {0} 自动升级失败，GhostSlacking 已恢复运行。请重试或查看日志。",
        "downloadAndInstall" => "下载并安装",
        "cancelDownload" => "取消下载",
        "skipVersion" => "跳过此版本",
        "resumeReminders" => "恢复提醒",
        "viewRelease" => "查看发布页面",
        "updateWindowTitle" => "GhostSlacking 软件更新",
        "updateWindowVersion" => "从 {0} 更新到 {1}",
        "updateWindowNoRelease" => "软件更新",
        "releaseNotesVersion" => "版本 {0}",
        "noReleaseNotes" => "此版本暂无更新说明。",
        "releaseHistoryIncomplete" => "部分历史更新说明未能加载；这不会影响安装包校验或更新。",
        "portableUpdateDescription" => "当前副本不是从 MSI 安装，无法在应用内升级；你仍可查看更新内容并从发布页面下载安装包。",
        "viewUpdateDetails" => "查看更新内容",
        "later" => "稍后",
        "revealAppearance" => "REVEAL 外观",
        "peekBehavior" => "PEEK 操作",
        "windowActions" => "窗口操作",
        "applicationActions" => "应用操作",
        "startupAndSafety" => "启动与安全",
        "languageAndDiagnostics" => "语言与诊断",
        "dataAndDiagnostics" => "数据与诊断",
        "diameter" => "Reveal 直径",
        "diameterDescription" => "光标周围可见区域的大小",
        "diameterStep" => "直径调整步长",
        "diameterStepDescription" => "每次使用增减快捷键改变的像素数",
        "softEdgeWidth" => "羽化范围",
        "softEdgeWidthDescription" => "清晰 Reveal 外侧的毛玻璃扩散范围，设为 0 可关闭",
        "blurLevel" => "模糊等级",
        "blurLevelDescription" => "选择整个羽化区域使用的单一模糊强度",
        "blurLow" => "轻度",
        "blurMedium" => "中度",
        "blurHigh" => "强",
        "shape" => "Reveal 形状",
        "shapeDescription" => "选择局部显示区域的轮廓",
        "circle" => "圆形",
        "rectangle" => "矩形",
        "roundedRectangle" => "圆角矩形",
        "peekKey" => "Peek 按键",
        "peekKeyDescription" => "触发局部显示时使用的单键",
        "peekFrameRateLimit" => "最大 Peek 帧率",
        "peekFrameRateLimitDescription" => "跟随鼠标所在显示器，且不会超过所选上限",
        "peekFrameRateAuto" => "自动（最高 120 FPS）",
        "pickHotkey" => "选择窗口",
        "pickHotkeyDescription" => "进入目标窗口选择模式",
        "windowToggleHotkey" => "窗口显隐",
        "windowToggleHotkeyDescription" => "切换当前目标的隐藏或显示状态",
        "diameterIncreaseHotkey" => "增大 Reveal 直径",
        "diameterIncreaseHotkeyDescription" => "按设置的步长增大当前及后续 Reveal",
        "diameterDecreaseHotkey" => "减小 Reveal 直径",
        "diameterDecreaseHotkeyDescription" => "按设置的步长减小当前及后续 Reveal",
        "restoreHotkey" => "恢复当前窗口",
        "restoreHotkeyDescription" => "恢复并解除当前目标窗口",
        "restoreAllHotkey" => "恢复所有窗口",
        "restoreAllHotkeyDescription" => "紧急恢复所有已隐藏窗口",
        "settingsHotkey" => "打开设置",
        "settingsHotkeyDescription" => "随时打开此设置窗口",
        "exitHotkey" => "退出应用",
        "exitHotkeyDescription" => "退出 GhostSlacking",
        "hotkeyNotSet" => "未设置",
        "pressKey" => "请按下按键",
        "pressShortcut" => "请按下组合键",
        "resetHotkey" => "重置为默认按键",
        "clearHotkey" => "清除快捷键",
        "resetSetting" => "恢复默认值",
        "duplicateHotkey" => "快捷键 {0} 已分配给多个操作，请为每个操作设置不同的组合键。",
        "selectWindowFirst" => "尚未选择目标窗口。请先执行“选择窗口”。",
        "peekMode" => "Peek 模式",
        "peekModeDescription" => "选择按住显示或按键切换",
        "holdPeek" => "按住显示",
        "togglePeek" => "按下切换",
        "restoreOnExit" => "退出时恢复窗口",
        "restoreOnExitDescription" => "关闭应用前自动恢复隐藏窗口",
        "startWindows" => "随 Windows 启动",
        "startWindowsDescription" => "登录系统后自动在托盘中运行",
        "logLevel" => "日志级别",
        "logLevelDescription" => "控制诊断日志记录的详细程度",
        "exportLogs" => "导出日志",
        "exportLogsDescription" => "将主程序、Watchdog 日志和诊断摘要导出为 ZIP 文件",
        "exportSettings" => "导出配置",
        "exportSettingsDescription" => "将当前已保存的配置导出为 JSON 文件，不包含未保存的修改",
        "selectExportDestination" => "选择导出位置",
        "exportSucceeded" => "导出成功",
        "exportPartiallySucceeded" => "已完成导出，但部分日志无法读取",
        "exportFailed" => "导出失败，请检查目标位置的写入权限",
        "interfaceLanguage" => "界面语言",
        "languageDescription" => "保存后更新应用界面语言",
        "theme" => "界面主题",
        "themeDescription" => "选择跟随系统，或固定使用浅色、深色外观",
        "themeSystem" => "跟随系统",
        "themeLight" => "浅色",
        "themeDark" => "深色",
        "cancel" => "取消",
        "save" => "保存",
        "ok" => "确定",
        "settingsModified" => "已修改",
        "saveSucceeded" => "已保存",
        "settingsSaveFailed" => "无法保存设置，请检查日志和配置文件权限。",
        "emergency" => "紧急恢复",
        _ => key
    } : key switch
    {
        "status" => "Status: {0} ({1})",
        "pick" => "Pick Window",
        "toggle" => "Toggle window visibility",
        "restore" => "Restore Window",
        "restoreAll" => "Restore All Windows",
        "settings" => "Settings",
        "updateAvailableTray" => "Update {0} available",
        "updateAvailableNotification" => "Version {0} is available. Click to review what's new.",
        "exit" => "Exit",
        "startupReady" => "GhostSlacking is running in the system tray.",
        "clickToPick" => "Window selection is active. Click the target window, or press Esc to cancel.",
        "pickCancelled" => "Window selection cancelled.",
        "noWindow" => "That window could not be selected. Click a visible app window and try again.",
        "windowSelected" => "{0} is now hidden. Use {1} to reveal it near the pointer.",
        "restoreSome" => "Some windows could not be restored. Run Restore All Windows again; if it still fails, check the log.",
        "pickFailed" => "Window selection could not start. Try again; if the problem continues, restart GhostSlacking.",
        "selectionStateCaptureFailed" => "That window could not be selected because its state could not be saved safely.",
        "ghostActivationFailed" => "The selected window could not be hidden. Check that it was restored normally.",
        "windowPlacementCorrectionFailed" => "The window position could not be preserved. Check that it was restored normally.",
        "hideWindowFailed" => "The target could not be hidden. Run Restore Window to leave hidden mode.",
        "revealWindowFailed" => "The local reveal could not be updated. Retry or run Restore Window.",
        "restoreFailed" => "The window could not be fully restored. Run Restore All Windows again or check the log.",
        "operationFailed" => "The operation could not be completed. Try again; if it still fails, check the log.",
        "settingsOpenFailed" => "Settings could not be opened. Try again; if it still fails, check the log.",
        "updateWindowOpenFailed" => "The update window could not be opened. Try again; if it still fails, check the log.",
        "unexpected" => "The app encountered an unexpected error. Try again; if it still fails, check the log.",
        "title" => "GhostSlacking Settings",
        "settingsCaption" => "Preferences",
        "settingsHint" => "Changes take effect after saving",
        "collapseSidebar" => "Collapse sidebar",
        "expandSidebar" => "Expand sidebar",
        "revealSettings" => "Reveal & Peek",
        "revealSettingsDescription" => "Adjust the Reveal appearance and how Peek behaves",
        "hotkeySettings" => "Keyboard shortcuts",
        "hotkeySettingsDescription" => "Assign global shortcuts to common actions",
        "generalSettings" => "General",
        "generalSettingsDescription" => "Manage appearance, startup, recovery, language, and diagnostics",
        "about" => "About",
        "aboutDescription" => "View the version, project links, and software updates",
        "aboutGhostSlacking" => "ABOUT GHOSTSLACKING",
        "aboutProductDescription" => "A lightweight Windows tool for hiding and locally revealing windows",
        "sourceRepository" => "GitHub project",
        "releasePage" => "Release page",
        "softwareUpdate" => "SOFTWARE UPDATE",
        "updateChannel" => "Update channel",
        "updateChannelDescription" => "Stable is used by default; the test channel includes beta and RC releases.",
        "updateChannelStable" => "Stable",
        "updateChannelTest" => "Test (includes pre-releases)",
        "currentVersion" => "Current version: {0}",
        "latestVersion" => "Latest version: {0}",
        "lastSuccessfulUpdateCheck" => "Last successful check: {0}",
        "noSuccessfulUpdateCheck" => "No successful update check yet",
        "checkUpdates" => "Check for updates",
        "checkingUpdates" => "Checking GitHub Releases for updates…",
        "upToDate" => "You are using the latest available version.",
        "updateNotChecked" => "Updates have not been checked during this run.",
        "updateAvailableDescription" => "Version {0} is available to download and install.",
        "updateSkippedDescription" => "Version {0} is skipped. You can still install it or resume reminders.",
        "downloadingUpdate" => "Downloading update… {0}%",
        "verifyingUpdate" => "Verifying installer integrity…",
        "startingInstaller" => "The installer is verified and the automatic update is being prepared…",
        "updateFailed" => "The update could not be checked, downloaded, or started. Check your connection and retry, or view the release page.",
        "updateCompleted" => "GhostSlacking was updated successfully to version {0}.",
        "updateCancelled" => "The software update was cancelled and GhostSlacking is running again.",
        "automaticUpdateFailed" => "The automatic update to version {0} failed. GhostSlacking is running again; retry or check the logs.",
        "downloadAndInstall" => "Download and install",
        "cancelDownload" => "Cancel download",
        "skipVersion" => "Skip this version",
        "resumeReminders" => "Resume reminders",
        "viewRelease" => "View release",
        "updateWindowTitle" => "GhostSlacking Software Update",
        "updateWindowVersion" => "Update from {0} to {1}",
        "updateWindowNoRelease" => "Software update",
        "releaseNotesVersion" => "Version {0}",
        "noReleaseNotes" => "No release notes are available for this version.",
        "releaseHistoryIncomplete" => "Some historical release notes could not be loaded. Installer verification and updating are unaffected.",
        "portableUpdateDescription" => "This copy was not installed with the MSI, so it cannot update in the app. You can still review what's new and download the installer from the release page.",
        "viewUpdateDetails" => "View what's new",
        "later" => "Later",
        "revealAppearance" => "REVEAL APPEARANCE",
        "peekBehavior" => "PEEK BEHAVIOR",
        "windowActions" => "WINDOW ACTIONS",
        "applicationActions" => "APPLICATION ACTIONS",
        "startupAndSafety" => "STARTUP & SAFETY",
        "languageAndDiagnostics" => "LANGUAGE & DIAGNOSTICS",
        "dataAndDiagnostics" => "DATA & DIAGNOSTICS",
        "diameter" => "Reveal diameter",
        "diameterDescription" => "Size of the visible area around the pointer",
        "diameterStep" => "Diameter adjustment step",
        "diameterStepDescription" => "Pixels changed by each increase or decrease shortcut",
        "softEdgeWidth" => "Feather range",
        "softEdgeWidthDescription" => "Frosted-glass diffusion outside the clear Reveal; set to 0 to disable",
        "blurLevel" => "Blur level",
        "blurLevelDescription" => "Choose one blur strength for the entire feather area",
        "blurLow" => "Low",
        "blurMedium" => "Medium",
        "blurHigh" => "High",
        "shape" => "Reveal shape",
        "shapeDescription" => "Choose the outline of the locally visible area",
        "circle" => "Circle",
        "rectangle" => "Rectangle",
        "roundedRectangle" => "Rounded rectangle",
        "peekKey" => "Peek key",
        "peekKeyDescription" => "Single key used to trigger the local Reveal",
        "peekFrameRateLimit" => "Maximum Peek frame rate",
        "peekFrameRateLimitDescription" => "Follow the pointer display without exceeding the selected limit",
        "peekFrameRateAuto" => "Auto (up to 120 FPS)",
        "pickHotkey" => "Pick window",
        "pickHotkeyDescription" => "Enter target-window selection mode",
        "windowToggleHotkey" => "Window visibility",
        "windowToggleHotkeyDescription" => "Hide or show the current target",
        "diameterIncreaseHotkey" => "Increase Reveal diameter",
        "diameterIncreaseHotkeyDescription" => "Increase the current and future Reveal by the configured step",
        "diameterDecreaseHotkey" => "Decrease Reveal diameter",
        "diameterDecreaseHotkeyDescription" => "Decrease the current and future Reveal by the configured step",
        "restoreHotkey" => "Restore current window",
        "restoreHotkeyDescription" => "Restore and release the current target",
        "restoreAllHotkey" => "Restore all windows",
        "restoreAllHotkeyDescription" => "Emergency restore for every hidden window",
        "settingsHotkey" => "Open settings",
        "settingsHotkeyDescription" => "Open this settings window from anywhere",
        "exitHotkey" => "Exit application",
        "exitHotkeyDescription" => "Quit GhostSlacking",
        "hotkeyNotSet" => "Not set",
        "pressKey" => "Press a key",
        "pressShortcut" => "Press a shortcut",
        "resetHotkey" => "Reset to default",
        "clearHotkey" => "Clear shortcut",
        "resetSetting" => "Restore default value",
        "duplicateHotkey" => "The shortcut {0} is assigned to multiple actions. Assign a different shortcut to each action.",
        "selectWindowFirst" => "No target window is selected. Run Pick Window first.",
        "peekMode" => "Peek mode",
        "peekModeDescription" => "Choose between hold-to-show and press-to-toggle",
        "holdPeek" => "Hold to show",
        "togglePeek" => "Press to toggle",
        "restoreOnExit" => "Restore windows when exiting",
        "restoreOnExitDescription" => "Restore hidden windows before the app closes",
        "startWindows" => "Start with Windows",
        "startWindowsDescription" => "Run in the system tray after sign-in",
        "logLevel" => "Log level",
        "logLevelDescription" => "Control how much diagnostic detail is recorded",
        "exportLogs" => "Export logs",
        "exportLogsDescription" => "Export app and Watchdog logs with a diagnostic summary as a ZIP file",
        "exportSettings" => "Export settings",
        "exportSettingsDescription" => "Export the currently saved settings as JSON; unsaved changes are not included",
        "selectExportDestination" => "Choose export location",
        "exportSucceeded" => "Export completed",
        "exportPartiallySucceeded" => "Export completed, but some logs could not be read",
        "exportFailed" => "Export failed. Check write access to the selected location",
        "interfaceLanguage" => "Interface language",
        "languageDescription" => "Update the app language after saving",
        "theme" => "App theme",
        "themeDescription" => "Follow the system or always use the light or dark appearance",
        "themeSystem" => "Use system setting",
        "themeLight" => "Light",
        "themeDark" => "Dark",
        "cancel" => "Cancel",
        "save" => "Save",
        "ok" => "OK",
        "settingsModified" => "Modified",
        "saveSucceeded" => "Saved",
        "settingsSaveFailed" => "Settings could not be saved. Check the log and configuration file permissions.",
        "emergency" => "Emergency Restore",
        _ => key
    };

    public static string PeekKeyName(UiLanguage language, int virtualKey)
    {
        var name = virtualKey switch
        {
            0x08 => language == UiLanguage.Chinese ? "退格" : "Backspace",
            0x09 => "Tab",
            0x0D => language == UiLanguage.Chinese ? "回车" : "Enter",
            0x10 => "Shift",
            0x11 => "Ctrl",
            0x12 => "Alt",
            0x13 => "Pause",
            0x14 => language == UiLanguage.Chinese ? "Caps Lock" : "Caps Lock",
            0x1B => language == UiLanguage.Chinese ? "Esc" : "Esc",
            0x20 => language == UiLanguage.Chinese ? "空格" : "Space",
            0x21 => language == UiLanguage.Chinese ? "Page Up" : "Page Up",
            0x22 => language == UiLanguage.Chinese ? "Page Down" : "Page Down",
            0x23 => language == UiLanguage.Chinese ? "End" : "End",
            0x24 => language == UiLanguage.Chinese ? "Home" : "Home",
            0x25 => language == UiLanguage.Chinese ? "左方向键" : "Left Arrow",
            0x26 => language == UiLanguage.Chinese ? "上方向键" : "Up Arrow",
            0x27 => language == UiLanguage.Chinese ? "右方向键" : "Right Arrow",
            0x28 => language == UiLanguage.Chinese ? "下方向键" : "Down Arrow",
            0x2C => language == UiLanguage.Chinese ? "截图键" : "Print Screen",
            0x2D => language == UiLanguage.Chinese ? "Insert" : "Insert",
            0x2E => language == UiLanguage.Chinese ? "Delete" : "Delete",
            0x5B => language == UiLanguage.Chinese ? "左 Windows" : "Left Windows",
            0x5C => language == UiLanguage.Chinese ? "右 Windows" : "Right Windows",
            0x90 => "Num Lock",
            0x91 => "Scroll Lock",
            0xA0 => language == UiLanguage.Chinese ? "左 Shift" : "Left Shift",
            0xA1 => language == UiLanguage.Chinese ? "右 Shift" : "Right Shift",
            0xA2 => language == UiLanguage.Chinese ? "左 Ctrl" : "Left Ctrl",
            0xA3 => language == UiLanguage.Chinese ? "右 Ctrl" : "Right Ctrl",
            0xA4 => language == UiLanguage.Chinese ? "左 Alt" : "Left Alt",
            0xA5 => language == UiLanguage.Chinese ? "右 Alt" : "Right Alt",
            _ when virtualKey is >= 0x30 and <= 0x39 => ((char)virtualKey).ToString(),
            _ when virtualKey is >= 0x41 and <= 0x5A => ((char)virtualKey).ToString(),
            _ when virtualKey is >= 0x60 and <= 0x69 => $"NumPad {virtualKey - 0x60}",
            _ when virtualKey is >= 0x70 and <= 0x7B => $"F{virtualKey - 0x6F}",
            _ => language == UiLanguage.Chinese ? $"按键 0x{virtualKey:X2}" : $"Key 0x{virtualKey:X2}"
        };

        return name;
    }

    public static string ShortcutName(UiLanguage language, HotkeyBinding binding)
    {
        if (binding.IsDisabled)
        {
            return Text(language, "hotkeyNotSet");
        }

        var parts = new List<string>();
        if (binding.Modifiers.HasFlag(ShortcutModifiers.Control))
        {
            parts.Add("Ctrl");
        }

        if (binding.Modifiers.HasFlag(ShortcutModifiers.Alt))
        {
            parts.Add("Alt");
        }

        if (binding.Modifiers.HasFlag(ShortcutModifiers.Shift))
        {
            parts.Add("Shift");
        }

        parts.Add(PeekKeyName(language, binding.VirtualKey));
        return string.Join("+", parts);
    }

    public static string Error(UiLanguage language, UserErrorKind kind) => Text(language, kind switch
    {
        UserErrorKind.SelectionStateCaptureFailed => "selectionStateCaptureFailed",
        UserErrorKind.GhostActivationFailed => "ghostActivationFailed",
        UserErrorKind.WindowPlacementCorrectionFailed => "windowPlacementCorrectionFailed",
        UserErrorKind.HideWindowFailed => "hideWindowFailed",
        UserErrorKind.RevealWindowFailed => "revealWindowFailed",
        UserErrorKind.RestoreFailed => "restoreFailed",
        _ => "operationFailed"
    });
}
